name: Parse outputs
on:
  schedule:
    - cron: "9 9 * * *"
  workflow_dispatch:
permissions:
  contents: write
  id-token: write
jobs:
  cleanup:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/sparecores/sc-inspector:main
      env:
        GITHUB_TOKEN: ${{ secrets.INSPECTOR_TOKEN }}
        PULUMI_BACKEND_URL: ${{ secrets.PULUMI_BACKEND_URL }}
        REPO_PATH: /repo/sc-inspector-data
      volumes:
        - ${{ github.workspace }}/sc-inspector-data:/repo/sc-inspector-data
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
          path: sc-inspector-data
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          role-to-assume: ${{ secrets.SC_RUNNER_ROLE_ARN }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: us-east-1
      - name: inspector
        run: python /inspector/inspector.py parse
