name: Parse outputs
on:
  schedule:
    - cron: "9 9 * * *"
  workflow_dispatch:
permissions:
  contents: write
  id-token: write
jobs:
  parse:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/sparecores/sc-inspector:main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
        REPO_PATH: /repo/sc-inspector-data
      volumes:
        - ${{ github.workspace }}/sc-inspector-data:/repo/sc-inspector-data
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
          path: sc-inspector-data
      - name: inspector
        run: python /inspector/inspector.py parse
