name: test
on:
  workflow_dispatch:
permissions:
  contents: write
  id-token: write
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: configure aws credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.SC_RUNNER_ROLE_ARN }}
      - name: get caller identity
        run: |
          aws sts get-caller-identity
